{% set name = "sphinxcontrib-mermaid" %}
{% set version = "2.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib_mermaid-{{ version }}.tar.gz
  sha256: a6865ef6b65b225c5403a3170de63a04a07227cada11a4a71a6b87b4f9ed185a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - python >={{ python_min }}
    - pyyaml
    - sphinx

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mgaitan/sphinxcontrib-mermaid
  summary: Mermaid diagrams in yours Sphinx powered docs
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - conda-forge/sphinx
    - ericpre
