{% set name = "sphinxcontrib-mermaid" %}
{% set version = "2.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/sphinxcontrib_mermaid-{{ version }}.tar.gz
  sha256: cf4f7d453d001132eaba5d1fdf53d42049f02e913213cf8337427483bfca26f4

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools
  run:
    - python >={{ python_min }}
    - pyyaml
    - sphinx

test:
  imports:
    - sphinxcontrib
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/mgaitan/sphinxcontrib-mermaid
  summary: Mermaid diagrams in yours Sphinx powered docs
  license: BSD-2-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - timkpaine
    - conda-forge/sphinx
    - ericpre
